name: Generate connector capabilities

on:
  push:
    branches:
      - main

jobs:
  calculate-capabilities:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELENG_GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -o connector ./cmd/baton-wiz

      - name: Run and save output
        env:
          BATON_WIZ_CLIENT_ID: ${{ secrets.BATON_WIZ_CLIENT_ID }}
          BATON_WIZ_CLIENT_SECRET: ${{ secrets.BATON_WIZ_CLIENT_SECRET }}
          BATON_AUTH_URL: 'https://auth.app.wiz.io/oauth/token'
          BATON_ENDPOINT_URL: 'https://api.us83.app.wiz.io/graphql'
          BATON_TAGS: ${{ secrets.BATON_TAGS }}
        run: ./connector capabilities > baton_capabilities.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updating baton capabilities.'
          add: 'baton_capabilities.json'